### PR TITLE
made navbar-fixed & improved the design

### PR DESCRIPTION
**Pull request by digambar-t7**

### CODE REVIEW

**Comment by yessGlory17** [comment]
I like your change. However, the boundaries of the links must remain intact. I will accept your pr when you make the correction.
Thanks @digambar-t7

**Comment by digambar-t7** [comment]
I didn't you can you elaborate it

**Comment by yessGlory17** [comment]
Hovering over the navigation bar links should look like the example below.


image

**Comment by yessGlory17** [comment]
thanks for the contribution

**Pull request merged**
